[package]
name = "finance-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
toml = "0.8"
ta = "0.5.0"
time = "0.3.36"
tokio = "1.39.3"
tokio-test = "0.4.4"
yahoo_finance_api = "2.2.1"
anyhow = "1.0.86"
